---
 
 - hosts: all
   become: true
   tasks:
 
   - name: get rpi model and memory information
     tags: shellcmds
     ansible.builtin.shell: |
       cat /proc/cpuinfo | grep "Model"
       free -h
       df -h
     register: command_output

   - name: Print to console
     debug:
       msg: "{{command_output.stdout}}"
